remove libbsd
squid-cache/squid pull request #1037
Opened 2022-04-28 10:12 UTC by guijan

Squid links against libbsd, but doesn't actually use any of its functions. 
It's easy to verify because you have to include the headers in the <bsd/*> subdirectory to use it if you don't use _pkg-config_ and _libbsd-overlay_, and `grep -R 'bsd/' .` in the squid repo doesn't find anything.

I've build tested this on Alpine Linux.

2022-04-28 10:43 UTC, kinkie commented
Most of the changes are formatting related, it might be better to split the PR in two, one with the formatting changes and one with the libbsd related change

Also, strlcpy is a strong ask on openbsd due to security concerns. I'd encourage to try and build on that platform first - the build farm openbsd node is broken right now however, I plan to revive it in a few days

2022-04-28 10:52 UTC, yadij commented
strlcpy() itself has not been used for a long while. Though there are other functions provided by the library which would have been affecting ./configure symbol detection (eg the MD5 library API) once ```-lbsd``` is in LIBS.

@kinkie, this library is for non-BSD environments to access API which is provided by BSD natively. So testing for its removal should be most useful on all non-BSD nodes.

2022-04-28 10:52 UTC, yadij commented
OK to test

2022-04-28 13:22 UTC, rousskov requested changes
Thank you for detecting and removing this unused code/library! If you can, please remove whitespace-only changes unrelated to libsd removal. Otherwise, please let me know and I will add the corresponding fixup myself.

2022-04-28 15:33 UTC, rousskov commented
> I've also changed the commit title to match the edited PR title.

Just FYI: PR branch commit message(s) are not used in the (effectively squashed by GitHub) official commit that will be added to master. We use PR title/description instead. There is no need to adjust PR branch commit messages or manually squash PR branch commits. See [Anubis](https://github.com/measurement-factory/anubis/blob/master/README.md#commit-message) documentation for details.

2022-04-28 15:38 UTC, rousskov approved these changes
Thank you for addressing the whitespace concern. I am not clearing this PR for merging (yet) because this is not my area of expertise, but I hope that others will do so soon.

2022-04-28 16:40 UTC, yadij approved these changes

2022-04-30 12:42 UTC, closed without merging

2022-05-07 17:19 UTC, guijan commented
Sorry to notify you guys, I'm just mentioning another PR here to add a mention there.
https://github.com/openwrt/openwrt/pull/9714