Maintenance: Reduce HTTP/FTP code duplication
squid-cache/squid pull request #1060
Opened 2022-05-26 19:09 UTC by eduard-bagdasaryan

Removed code duplication  probably caused bug fixed in commit 049eeeb.

2022-05-26 20:09 UTC, rousskov approved these changes
Nice, thank you!

Our `ftp_port` documentation already implies that `worker-queues` should be honored. I assume that the option is already accepted by the official code when parsing `ftp_port` configuration. We just did not pass the option to Comm when creating listening sockets (in `ftp_port` cases). Please correct me if my assumptions are wrong.

2022-05-27 12:26 UTC, yadij requested changes
Please use separate PR for code cleanup (large clientHttpConnectionsOpen changes) and feature addition (small clientStartListeningOn changes).

2022-05-29 22:35 UTC, eduard-bagdasaryan commented
Separated into  [PR1061](https://github.com/squid-cache/squid/pull/1061).

2022-06-04 09:27 UTC, yadij approved these changes

2022-06-04 11:33 UTC, closed without merging