Remove duplicate pre-defines
squid-cache/squid pull request #1305
Opened 2023-03-11 08:11 UTC by yadij

2023-03-11 09:54 UTC, kinkie approved these changes

2023-03-11 15:48 UTC, rousskov requested changes
I support the removal, but it should not be done at the expense of adding a `base/forward.h` dependency to `clients/forward.h`, especially since you have started to police indirect duplicates in header inclusion. Please adjust those source files that actually need `base/forward.h` instead. Please see one of the change requests for details and discussion.

2023-03-11 15:48 UTC, rousskov commented on src/clients/forward.h
> +#include "base/forward.h"
To minimize dependencies among headers, `X.h` should not include `Y.h` when `X.h` does not need `Y.h` to be compiled. In Squid `src/` context, that "to be compiled" phrase means "to be compiled in a hypothetical translation unit that includes `squid.h`, `X.h`, and no other header or code".

Applying the above rule to this PR means that `clients/forward.h` should not add a dependency on `base/forward.h`:

```suggestion
```

Needless to say, other source code adjustments may be necessary to properly remove AsyncJobPointer typedef from `clients/forward.h`. The suggestion in this change request is just the first step and may, in isolation, break the build.

P.S. There is a weaker rule of thumb (based on the above minimization rule) that excepts situations where X cannot be compiled without Y in any _realistic_ translation unit, but even that weaker version cannot justify adding `base/forward.h` to `clients/forward.h`.

2023-03-11 15:48 UTC, rousskov commented on src/clients/forward.h
> -typedef CbcPointer<AsyncJob> AsyncJobPointer;
> PR description: Remove some duplicate pre-defines

I adjusted the PR title to use more accurate C++ terms for "pre-defines": "typedef and forward declarations". I do not insist on the PR title change. Please feel free to revert or adjust as needed.

2023-03-12 23:03 UTC, rousskov approved these changes

2023-03-13 13:36 UTC, closed without merging