Prepare changelog for v6.0.3
squid-cache/squid pull request #1374
Opened 2023-06-03 19:12 UTC by kinkie

2023-06-03 19:32 UTC, yadij requested changes

2023-06-03 19:32 UTC, yadij commented on ChangeLog
> +	- Maintenance: update release process script
this script is not part of the released code, so ca be elided.
```suggestion
```

2023-06-03 19:32 UTC, yadij commented on ChangeLog
> +Changes in squid-6.0.3 (5 Jun 2023):
please keep the (slightly weird) 2-digit format.
```suggestion
Changes in squid-6.0.3 (05 Jun 2023):
```

2023-06-04 15:25 UTC, yadij approved these changes

2023-06-04 17:01 UTC, rousskov approved these changes

2023-06-04 19:25 UTC, closed without merging