MinGW: fix winsock dependency issues
squid-cache/squid pull request #1375
Opened 2023-06-04 17:46 UTC by yadij

error: warning: Please include winsock2.h before windows.h

Also, detect these headers early to fix autoconf tests within
MinGW environments.

Also, cleanup these header includes across all Squid code
built for MinGW.

2023-06-04 17:47 UTC, yadij commented
Waiting for PR #1341

2023-06-23 15:05 UTC, yadij commented
Removed the dependency on PR https://github.com/squid-cache/squid/pull/1341

2023-06-23 15:31 UTC, rousskov requested changes

2023-07-02 09:15 UTC, yadij commented on configure.ac
> +    AC_CHECK_HEADERS([ws2tcpip.h winsock2.h windows.h],,,[
Thanks, fixed in [b512ebf](https://github.com/squid-cache/squid/pull/1375/commits/b512ebfc58351129904b2f9c1987bf2355726b1d)

2023-07-02 13:46 UTC, rousskov approved these changes

2023-07-02 17:34 UTC, closed without merging