Implement cache_log_message id 69
squid-cache/squid pull request #1481
Opened 2023-09-17 14:52 UTC by kinkie

Log message:
WARNING: Unsupported or unexpected from-helper annotation
with a name reserved for Squid use

has been found to be spamming some users, as it would be
emitted with every helper response.
In order to enable using the
cache_log_message id=... limit=...
directive, instrument the log message so it can be used with it

2023-09-17 14:52 UTC, kinkie commented
Supersedes PR #1464

2023-09-18 14:09 UTC, rousskov requested changes
I adjusted PR title to be more revealing in `git log --oneline` summaries and PR description to avoid the possible implication that all these messages is bogus/unwanted spam (and to improve formatting/presentation). Please adjust further as needed.

2023-09-18 14:43 UTC, kinkie commented on doc/debug-messages.dox
> +69 WARNING: Unsupported or unexpected from-helper annotation ...
Thanks. I had to reverse engineer how to do this, hence the attempt at documenting. Will do

2023-09-18 15:05 UTC, rousskov approved these changes

2023-09-19 03:18 UTC, yadij approved these changes

2023-09-19 08:33 UTC, closed without merging

2023-09-19 18:15 UTC, squidadm commented
queued for backport to v6