Avoid UB when packing name
squid-cache/squid pull request #1613
Opened 2023-12-05 18:51 UTC by jtstrs

Function rfc1035LabelPack put ```nullptr``` as argument
for memcpy function, which is undefined behaviour

2023-12-05 18:54 UTC, jtstrs commented
Using ```memcpy``` is undefined behiour according to
https://en.cppreference.com/w/cpp/string/byte/memcpy
> If either dest or src is an [invalid or null pointer], 
> the behavior is undefined, even if count is zero.

2023-12-05 19:46 UTC, rousskov requested changes
Thank you for working on fixing this bug!

2023-12-05 19:46 UTC, rousskov commented on src/dns/rfc1035.cc
> +    *(buf + off) = 0;
I am not sure, but it looks like the proposed code might overwrite the supplied buffer. For example, that overwrite may happen during rfc1035NamePack("", 0, "test").

AFAICT, the official code asserts in that case because the second (i.e. post-loop or terminating) rfc1035LabelPack() call runs out of space; the corresponding assertion is inside rfc1035LabelPack(): `assert(sz >= len + 1)`. PR effectively replaces that assertion (during buffer-termination) with custom and overly optimistic code.

We do not want either outcome, but if we have to pick between the two evils in this terrible code, it is better to assert than to overwrite.

P.S. When you modify C++ code, please use const and [AAA](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/) as much as possible.

2023-12-05 21:54 UTC, yadij commented on src/dns/rfc1035.cc
> +    *(buf + off) = 0;
Also, please use explicit `'\0'` character instead of `0` to avoid injecting more than 1 byte.

2023-12-05 21:54 UTC, rousskov commented on src/dns/rfc1035.cc
> +    *(buf + off) = 0;
> For example, that overrun may happen during rfc1035NamePack("", 0, "test").

I suspect that my (extreme) example does not really work because strtok("") will return a non-nil string and we will will enter the loop (and then assert inside rfc1035LabelPack() instead of overflowing the buffer).

However, I still think that this change request is valid -- the underlying problem does exist; we just need a more complex test to trigger it. Perhaps something like the test case below would trigger buffer overflow in the new termination code?

```C++
char buf[2];
// the loop will pack char(1) and character 'A', returning offset 2;
// the termination code will write into an off-limits  `buf + 2` memory
rfc1035NamePack(buf, sizeof(buf), "A"); // needs 3 bytes but is given 2
```

2023-12-12 15:54 UTC, jtstrs commented on src/dns/rfc1035.cc
> +    *(buf + off) = 0;
Such cases should handle by assertion at the end of ```rfc1035NamePack``` function. (There is also true for test suggested by you) https://godbolt.org/z/r511j47b7
But that assertion happening only after editing of buffer, so probably moving this assertion before adding null-term label should solve possible problem, i.e.

```
// Ensure that no buffer overflow there
assert(off + 1 <= sz);
// Put terminate NULL label at the end
*(buf + off) = 0;
off++;

return off;
```

What do you think about this proposal?

2023-12-12 17:05 UTC, rousskov commented on src/dns/rfc1035.cc
> +    *(buf + off) = 0;
> Such cases should handle by assertion at the end of rfc1035NamePack function. (There is also true for test suggested by you) https://godbolt.org/z/r511j47b7

I agree that such cases should be handled by an assertion in rfc1035NamePack(), but rfc1035NamePack() must assert _before_ overflowing the buffer, not _after_ overflowing it! After an overflow, the problem that the assertion needs to prevent cannot be prevented; the game has been lost.

>  But that assertion happening only after editing of buffer, so probably moving this assertion before adding null-term label should solve possible problem

Exactly. Here is a (slightly) better sketch:

```C++
// add a terminating 0-size label
assert(off < sz);
buf[off] = 0;
++off;

return off;
```

2023-12-12 17:11 UTC, jtstrs commented on src/dns/rfc1035.cc
> +    *(buf + off) = 0;
Got it

2023-12-13 16:04 UTC, rousskov approved these changes
Thank you for addressing my primary concern. I am approving this PR after polishing its code and PR metadata a little. @jtstrs, please double check my changes.

2023-12-17 07:13 UTC, yadij approved these changes
We still have the UB implied by potential `memcpy()` mistakes. But replacing the one in label packing with `memove()` can be done when the other ones are updated.

2023-12-17 07:13 UTC, yadij commented on src/dns/rfc1035.cc
> -    off += rfc1035LabelPack(buf + off, sz - off, nullptr);
Either implementation is fine with me.

2023-12-21 16:59 UTC, rousskov commented
OK to test

2023-12-22 11:32 UTC, kinkie commented
OK to test

2023-12-24 21:49 UTC, kinkie approved these changes

2023-12-25 02:20 UTC, closed without merging