Fix potentinal use of nullptr in usePinned
squid-cache/squid pull request #1619
Opened 2023-12-13 10:45 UTC by jtstrs

```request->pinnedConnection()``` can return nullptr
Code inside ```try``` block suggest that connManager
will valid ptr. Added assertion for this

2023-12-13 15:11 UTC, rousskov requested changes
> PR description: Fix potentinal use of nullptr in usePinned

There is no potential for a nil pointer dereference here AFAICT, but this PR does highlight at least two "code quality" problems that can and should be addressed. I left the corresponding detailed change request.

BTW, in most cases, if there is a known nil pointer dereference, it cannot be _properly_ addressed by adding an assertion: Assertions are meant for conditions we believe to be always true (rather than for properly handling a known false case).

2023-12-13 15:11 UTC, rousskov commented on src/tunnel.cc
> +    Assure(request);
Please undo this out-of-scope and distracting improvement:

```suggestion
    Must(request);
```

In the future, please avoid out-of-scope changes (by default).

2023-12-14 17:07 UTC, rousskov approved these changes
Thank you.

2023-12-14 17:14 UTC, rousskov commented
I adjusted PR title/description to match the current PR code. @jtstrs, in the future, please keep that metadata up-to-date because it will be [used](https://github.com/measurement-factory/anubis/blob/master/README.md#commit-message) for the commit message when merging this PR.

2023-12-14 17:19 UTC, rousskov commented
@jtstrs, Squid automation scripts identify the author of your contributions as `Alex <bigalex934@gmail.com>` because that is what you have in your GitHub account. That string will be added to CONTRIBUTORS _unless_ you tell me to adjust it (e.g., to add a last name or to change the email address). If you would like to adjust, please let me know!

2023-12-14 18:40 UTC, jtstrs commented
>  I adjusted PR title/description to match the current PR code. @jtstrs, in the future, please keep that metadata up-to-date because it will be [used](https://github.com/measurement-factory/anubis/blob/master/README.md#commit-message) >  for the commit message when merging this PR.

Good, will take it into account

> @jtstrs, Squid automation scripts identify the author of your contributions as Alex <bigalex934@gmail.com> because that is what you have in your GitHub account. That string will be added to CONTRIBUTORS unless you tell me to adjust it (e.g., to add a last name or to change the email address). Not adding anything to CONTRIBUTORS is also allowed (but discouraged). If you would like to adjust something, please let me know!

Its ok, but anyway thank you for highlighting that

2023-12-14 19:56 UTC, rousskov commented
> Its ok, but anyway thank you for highlighting that

The latest [application](https://github.com/squid-cache/squid/actions/runs/7207176081/job/19633500502?pr=1619#step:4:52) of the same script picked up another variation:

```diff
+ Alex <bigalex934@gmail.com>
+ Alexey Simakov <bigalex934@gmail.com>
```

If you do not have another preference, we will use the latter/second variant because it has more information.

2023-12-16 09:50 UTC, kinkie approved these changes

2023-12-16 21:32 UTC, closed without merging