Docs: update doxygen supprot
squid-cache/squid pull request #1622
Opened 2023-12-17 16:25 UTC by yadij

* Doxygen 1.7.5 changes the HTML tag nesting.

Fix our doxygen.header.dyn template to un-break the website
generated content.

* Doxygen 1.8 added Markdown support.

Add .md to the acceptable file extensions. We should move to
these for feature or component documentation instead of the
custom foo.dox files with c/c++ code comments we currently use.

Also, disable IDL_PROPERTY_SUPPORT which has been causing some
errors with output getter/setter matching in the generated
output.

2023-12-17 16:28 UTC, kinkie submitted a review, later dismissed

2023-12-18 14:49 UTC, rousskov requested changes
Please share a pointer to the resulting diff exposing changes in Doxygen-generated content.

2023-12-28 19:03 UTC, kinkie approved these changes

2023-12-28 19:35 UTC, rousskov requested changes
Please share a pointer to the resulting diff exposing changes in Doxygen-generated content.

2023-12-28 19:35 UTC, rousskov commented on squid.dox
> +                         *.md
> Dropping that change from this PR.

Please do not forget to update this PR description accordingly.

2023-12-29 10:27 UTC, yadij commented on squid.dox
> +                         *.md
Yes, already done.

2023-12-29 11:12 UTC, yadij commented
> Please share a pointer to the resulting diff exposing changes in Doxygen-generated content.

The first change; to the `doxygen.header.dyn` file is 7154 chunks identical to the PR diff for `doxygen.header.dyn` - one for every  `.dyn` produced in the output. These fix the display bug(s) you can see (for now) by visiting http://www.squid-cache.org/Doc/code/ :
 * the site menu is rendered outside the main content column area, and
 * the `navmenu` generator scripts abort with an error updating the page DOM. Leaving no tabbed menu for visitors to browse the code docs with.

The second change; to the `squid.dox` file is a bit subtle. The bug it fixes shows up in some of the images and reference lists for members, only for output produced by recent doxygen versions where the IDL hints are enabled by default.
 It can be seen in the doxygen.log error/warnings list as entries like this:
```
/src/squid/yadij-git/src/auth/basic/Config.cc:70: warning: no uniquely matching class member found for
  const char * Auth::Basic::Config::type() const
Possible candidates:
  'int snmp_mib_tree::type' at line 56 of file /src/squid/yadij-git/include/parse.h
  'u_char variable_list::type' at line 48 of file /src/squid/yadij-git/include/snmp_vars.h
  'int32_t _ntlmhdr::type' at line 82 of file /src/squid/yadij-git/lib/ntlmauth/ntlmauth.h
  'int node::type' at line 109 of file /src/squid/yadij-git/lib/snmplib/parse.c
```
 ... where the candidates lists every class where the member name is used by a getter **OR** setter.


After this PR disabling the hints, doxygen correctly lists more of these candidate lists narrowing it down to only getter or setter. Am not sure why or what is going on - but we are not producing IDL hint files so disabling that unused feature entirely for now.

2024-01-07 09:06 UTC, kinkie commented
ok to test

2024-01-09 20:22 UTC, yadij commented
header regenrated using:
 ```
doxygen -w html header.out footer.out style.css squid.dox
```

2024-01-11 07:10 UTC, closed without merging