Prep changelog for 6.8
squid-cache/squid pull request #1712
Opened 2024-02-28 14:53 UTC by kinkie

2024-02-28 14:55 UTC, kinkie commented
Note: this PR is against v6; once accepted, it will need to be forward-ported to master

2024-02-28 15:40 UTC, rousskov commented
Thank you for keeping these v6-specific changes to the v6 branch!

2024-02-28 15:44 UTC, rousskov commented
> this PR is against v6; once accepted, it will need to be forward-ported to master

... but there is no rush with that second/porting step. We can even sync ChangeLog around v7 branching time!

2024-02-28 16:06 UTC, yadij requested changes

2024-02-29 00:18 UTC, kinkie commented on configure.ac
> +AC_INIT([Squid Web Proxy],[6.8-VCS],[https://bugs.squid-cache.org/],[squid])
reverted.

2024-02-29 14:54 UTC, rousskov commented on configure.ac
> +AC_INIT([Squid Web Proxy],[6.8-VCS],[https://bugs.squid-cache.org/],[squid])
> reverted

@kinkie, FWIW, I doubt Amos was actually requesting a reversal of AC_INIT() change, but, if, for whatever reason, you do _not_ want this PR commit to be the "formal release" commit, should not the title of this PR be updated again?

2024-02-29 14:58 UTC, kinkie commented on configure.ac
> +AC_INIT([Squid Web Proxy],[6.8-VCS],[https://bugs.squid-cache.org/],[squid])
Title updated.
I think it's safest to rollback and to stick to established procedure. I'm already testing new ground, let's do one change at a time

2024-03-01 01:07 UTC, yadij approved these changes

2024-03-01 01:10 UTC, yadij commented on configure.ac
> +AC_INIT([Squid Web Proxy],[6.8-VCS],[https://bugs.squid-cache.org/],[squid])
Well, established procedure is to merge these documentation changes to master. So that line has already broken.

2024-03-04 05:35 UTC, merged