Convert hostname_aliases to SBufList
squid-cache/squid pull request #1737
Opened 2024-03-14 04:04 UTC by yadij

Container-only change, no behaviour changes.

2024-03-14 05:45 UTC, kinkie submitted a review, later dismissed

2024-03-14 14:29 UTC, rousskov requested changes

2024-03-14 14:29 UTC, rousskov commented on src/client_side_request.cc
> +    if (internalHostnameIs(SBuf(request->url.host())) && request->url.port() == getMyPort()) {
Please reorder to reduce the number of cases applicable to this PR-added performance regression:

```suggestion
    if (request->url.port() == getMyPort() && internalHostnameIs(SBuf(request->url.host()))) {
```

Alternatively, you can leave internalHostnameIs() parameter type unchanged in this PR and continue to compare with a c-string until Uri::host() itself is converted to SBuf. Your call.

2024-03-14 14:56 UTC, yadij commented on src/internal.cc
> +        if (w.caseCmp(arg) == 0)
done

2024-03-14 15:46 UTC, rousskov approved these changes
Thank you.

2024-03-15 05:56 UTC, kinkie approved these changes
👍🏼

2024-03-15 16:16 UTC, closed without merging