Have SQUID_CHECK_LIB_WORKS do state SAVE/RESTORE
squid-cache/squid pull request #1774
Opened 2024-04-05 05:36 UTC by yadij

Removing a lot of duplicated code.

2024-04-05 08:28 UTC, kinkie approved these changes
Good idea!

2024-04-05 15:05 UTC, rousskov requested changes

2024-04-05 17:48 UTC, yadij commented on acinclude/squid-util.m4
>    AS_IF([! test -z m4_toupper(m4_translit(["$LIB$1_LIBS"], [-+.], [___]))],[
I spent today checking that one to verify.
 * It does appear that the comment a few lines above about `LT_INIT pulling it in somehow is correct. I was not able to detect any linker differences by removing this `LIBS=` update.
 * The `LIBDL_PATH` is already placed into `CPPFLAGS`, so  no effect from removing the global change to `LDFLAGS`

2024-04-05 17:59 UTC, yadij commented on acinclude/squid-util.m4
> +  SQUID_STATE_SAVE(check_lib_works_state)
Done in [41e29e9](https://github.com/squid-cache/squid/pull/1774/commits/41e29e9d1f64688ca209ace9c29e29aa89a3499b)

2024-04-06 20:03 UTC, rousskov requested changes
Almost done!

2024-04-07 14:01 UTC, rousskov approved these changes

2024-04-07 16:45 UTC, closed without merging