MinGW: Fix error: cannot convert 'size_t*' to 'int*
squid-cache/squid pull request #1825
Opened 2024-05-29 13:59 UTC by yadij

Removing another addrinfo as we do.

2024-05-29 20:01 UTC, rousskov requested changes

2024-05-30 08:58 UTC, yadij commented on src/comm/TcpAcceptor.cc
> +        details->local.setEmpty();
AFAIK this was only done for paranoia reasons. Removing.

2024-05-30 10:24 UTC, yadij commented on src/comm/TcpAcceptor.cc
> +    socklen_t localAddrSz = sizeof(localAddr);
Done in 849a25b845

2024-05-30 10:24 UTC, yadij commented on src/comm/TcpAcceptor.cc
> +    details->local = localAddr;
Done in 849a25b845

2024-05-30 10:24 UTC, yadij commented on src/comm/TcpAcceptor.cc
>      if (rawSock < 0) {
Done in 849a25b845

2024-05-30 10:25 UTC, yadij commented on src/comm/TcpAcceptor.cc
> +        details->local.setEmpty();
Done in 849a25b845

2024-05-30 14:38 UTC, rousskov approved these changes
Thanks a lot for this cleanup!

P.S. We should avoid (poor) code duplication that this PR and recent 1800e254 are creating, but I think we should _continue_ to duplicate that code for a little bit longer before there are enough use cases to suggest a proper deduplication solution.

2024-06-01 09:35 UTC, kinkie approved these changes

2024-06-02 01:58 UTC, yadij commented
> Thanks a lot for this cleanup!
> 
> P.S. We should avoid (poor) code duplication that this PR and recent [1800e25](https://github.com/squid-cache/squid/commit/1800e254070002fc7ee3f4848e06fdbea00fd2fb) are creating, but I think we should _continue_ to duplicate that code for a little bit longer before there are enough use cases to suggest a proper deduplication solution.

I assume you are referring to the pattern of 2 local variables with a `reinterpret_cast` (if not please correct me). FWIW, I hope long term that we only need to de-duplicate the set/get syscalls and the rest are uncommon enough to be okay without anything special.

2024-06-02 04:30 UTC, closed without merging

2024-06-02 21:27 UTC, rousskov commented
> > P.S. We should avoid (poor) code duplication that this PR and recent [1800e25](https://github.com/squid-cache/squid/commit/1800e254070002fc7ee3f4848e06fdbea00fd2fb) are creating, but I think we should _continue_ to duplicate that code for a little bit longer before there are enough use cases to suggest a proper deduplication solution.
 
> I assume you are referring to the pattern of 2 local variables with a `reinterpret_cast` (if not please correct me).

The pattern includes two local variable definition/initialization code, a reinterpret_cast, an assertion, and a conversion to an Ip::Address object (at least).

> FWIW, I hope long term that we only need to de-duplicate the set/get syscalls and the rest are uncommon enough to be okay without anything special.

Yeah, let's see where these initial (and duplicated) changes lead us. I see no reason to discuss the details of that potential future duplication avoidance effort until we have more merged use cases. We are making good progress so far...