Bug fix: strlen(NULL) on invalid Digest header
squid-cache/squid pull request #1906
Opened 2024-09-28 16:57 UTC by kinkie

Fix a bug in Digest authentication where
on certain combination of parameters,
an invalid pointer would be dereferenced while
calculating the digest hash.

This bug was reported by Joshua Rogers
of Opera Software.

2024-09-29 23:28 UTC, yadij requested changes
Would it not be better to replace the c-string with SBuf?

Fir titles; please avoid redundant "Bug fix". If it needs a bug number, open a report and use that. Otherwise just say "Fix" (all fixes are bug fixes).

2024-09-29 23:28 UTC, yadij commented on src/auth/digest/Config.cc
> +        /* rfc7616 mandates qop to be present */
please reference where in the RFC this requirement is, so we can check easily,

2024-09-30 06:41 UTC, kinkie commented
> Would it not be better to replace the c-string with SBuf?

I'd like to keep the fix minimal

> Fir titles; please avoid redundant "Bug fix". If it needs a bug number, open a report and use that. Otherwise just say "Fix" (all fixes are bug fixes).

Done

2024-09-30 08:43 UTC, yadij commented on src/auth/digest/Config.cc
> +        /* rfc7616 section 3.3 mandates qop to be present */
Section 3.3 does not apply. This logic handles HTTP Request from the client.
As such the requirements to follow are in [RFC 7616 Section 3.4](https://www.rfc-editor.org/rfc/rfc7616#section-3.4).

```suggestion
        /* RFC7616 section 3.3, qop:
         * "MUST be used by all implementations"
         *
         * RFC7616 section 3.4, qop:
         *  "value MUST be one of the alternatives the server
         *   indicated it supports in the WWW-Authenticate header field"
         *
         * Squid sends qop=auth, reject buggy or outdated clients.
        */
```

2024-09-30 08:45 UTC, yadij approved these changes

2024-09-30 16:48 UTC, kinkie commented
> I think this PR should also add assertions to DigestCalcHA1() to prevent strlen(nullptr) calls on other code paths; it is better to assert than to crash. I do not insist on this additional PR change.

I thought about it, but then decided to keep it minimal for now. I'd rather move everything to SBuf, but most attempts at doing it are not good at sticking to a well bounded scope.

> I edited PR description to leave more breadcrumbs about the problem and to improve consistency in referencing Joshua-reported bugs. Please adjust further if needed and/or re-clear this PR for merging.

Thanks for doing that. As soon as this goes in, we can backport to v6 and cut a release.

2024-10-07 12:59 UTC, kinkie commented
ok to test

2024-10-08 16:02 UTC, closed without merging

2024-10-09 00:15 UTC, squidadm commented
queued for backport to v6