CI: show build commands on terminal
squid-cache/squid pull request #1965
Opened 2024-12-17 19:51 UTC by kinkie

test-builds.sh records build output in per-layer logs, and we are
already collecting those logs. Send build output to standard output as
well, to expose it in GitHub Actions user interface. This new detailed
output is enclosed in a "layer ... output" group to keep emphasizing
problematic output lines extracted by test-builds.sh.

Also enclose MacOS build setup output in a group, for similar reasons.

2024-12-17 22:57 UTC, rousskov requested changes
> test-builds.sh record output from the build in bt.log

It does not. Output is sent to _layer-specific_ log files.

> Send output from the build also to standard output, for more convenient reading in Github's 'actions' interface

I expect the result to be _less_ convenient for many, especially when the build fails (which is the primary use case here IMO!): Navigating long logs using GitHub Actions API is painful and archived logs are just a few mouse clicks away. If anything, we should be _reducing_ noise in the current GitHub Actions output.

I do not know whether it would help your use case, I would support adding the tail of a failed log to test-builds.sh output (even by default).

I also do not like proposed code duplication, but I hope that will go away while addressing the primary concern discussed above.

2024-12-17 23:55 UTC, kinkie commented
> > test-builds.sh record output from the build in bt.log
> 
> It does not. Output is sent to _layer-specific_ log files.

Markdown ate my homework. I had written "bt_layer_.log" . Correcting

> > Send output from the build also to standard output, for more convenient reading in Github's 'actions' interface
> 
> I expect the result to be _less_ convenient for many, especially when the build fails (which is the primary use case here IMO!): Navigating long logs using GitHub Actions API is painful and archived logs are just a few mouse clicks away. If anything, we should be _reducing_ noise in the current GitHub Actions output.

After this PR:
in case of failure to build a PR,
1. I click on "details" for the failed check in the "discussion" page
2. expand the appropriate section
3. fill in "search" with the relevant keyword, and then scroll through the logs. It's not great, but 90% of the ti
4. me it's sufficient. And for the other 10% I can still to the current workflow below, which is not going away

Before this PR:
in case of failure to build a PR,
1. I click on "details" for the failed check in the "discussion" page
2. expand the "publish search logs" section
3. search for the link to download the artifact
6. click on it to download it to local disk
7. switch to a terminal (or on MacOS, to the finder)
8. figure out where the file was downloaded
9. change to that directory
10. unzip the log file
11. open the uncompressed content with 'less' or any other similar program
12. search for the relevant keyword and scroll through the logs
13. delete the compressed and uncompressed logs from my local disk

I'm not sure what is your workflow, but for me this PR simplifies things significantly.

Anyone who prefers the "before" version of the workflow is unaffected: the 'Run' subsection of the workflow output with all the logs is closed by default, it doesn't occupy any more screen real estate than it does now.

In other words, this proposal improves things for at least me; I would like to get a concrete example of how it causes a measurable regression for you as a representatives of the many you mention


In fact, after this change, another workflow becomes possible if one has installed the _gh_ CLI tool:
1. `gh run list` - make a note of the "id field" corresponding to the workflow one is interested in 
2. `gh run view --log <id>`  downloads the on-screen output and opens it using `less`

> I do not know whether it would help your use case, I would support adding the tail of a failed log to test-builds.sh output (even by default).

It can help, but not as much as having the full log. Sometimes, especially in cases of high parallelism in builds, an error can be dozens of lines back from the end of the log

> I also do not like proposed code duplication, but I hope that will go away while addressing the primary concern discussed above.

We could make verbose output to be the default for test-builds.sh, but I expect it would be more disruptive than this change.  I am not sure if you had something else in mind

2024-12-18 07:28 UTC, kinkie commented
> > > test-builds.sh record output from the build in bt.log
> > 
> > 
> > It does not. Output is sent to _layer-specific_ log files.
> 
> Markdown ate my homework. I had written "bt_layer_.log" . Correcting
> 
> > > Send output from the build also to standard output, for more convenient reading in Github's 'actions' interface
> > 
> > 
> > I expect the result to be _less_ convenient for many, especially when the build fails (which is the primary use case here IMO!): Navigating long logs using GitHub Actions API is painful and archived logs are just a few mouse clicks away. If anything, we should be _reducing_ noise in the current GitHub Actions output.
> 
> After this PR: in case of failure to build a PR,
> 
> 1. I click on "details" for the failed check in the "discussion" page
> 2. expand the appropriate section
> 3. fill in "search" with the relevant keyword, and then scroll through the logs. It's not great, but 90% of the ti
> 4. me it's sufficient. And for the other 10% I can still to the current workflow below, which is not going away
> 
> Before this PR: in case of failure to build a PR,
> 
> 1. I click on "details" for the failed check in the "discussion" page
> 2. expand the "publish logs" section
> 3. search for the link to download the artifact
> 4. click on it to download it to local disk
> 5. switch to a terminal (or on MacOS, to the finder)
> 6. figure out where the file was downloaded
> 7. change to that directory
> 8. unzip the log file
> 9. open the uncompressed content with 'less' or any other similar program
> 10. search for the relevant keyword and scroll through the logs
> 11. delete the compressed and uncompressed logs from my local disk
> 
> I'm not sure what is your workflow, but for me this PR simplifies things significantly.
> 
> Anyone who prefers the "before" version of the workflow is unaffected: the 'Run' subsection of the workflow output with all the logs is closed by default, it doesn't occupy any more screen real estate than it does now.
> 
> In other words, this proposal improves things for at least me; I would like to get a concrete example of how it causes a measurable regression for you as a representatives of the many you mention
> 
> In fact, after this change, another workflow becomes possible if one has installed the _gh_ CLI tool:
> 
> 1. `gh run list` - make a note of the "id field" corresponding to the workflow one is interested in
> 2. `gh run view --log <id>`  downloads the on-screen output and opens it using `less`
> 
> > I do not know whether it would help your use case, I would support adding the tail of a failed log to test-builds.sh output (even by default).
> 
> It can help, but not as much as having the full log. Sometimes, especially in cases of high parallelism in builds, an error can be dozens of lines back from the end of the log
> 
> > I also do not like proposed code duplication, but I hope that will go away while addressing the primary concern discussed above.
> 
> We could make verbose output to be the default for test-builds.sh, but I expect it would be more disruptive than this change. I am not sure if you had something else in mind

2024-12-19 04:26 UTC, yadij approved these changes
Just one fix of a pre-existing bug that shows up in the touched lines of this PR.
I do not insist on this.

2024-12-19 04:26 UTC, yadij commented on .github/workflows/quick.yaml
> +        run: ./test-builds.sh --verbose ./test-suite/buildtests/layer-02-maximus.opts
```suggestion
        run: ./test-builds.sh --verbose layer-02-maximus
```

2024-12-19 07:52 UTC, kinkie commented
> Just one fix of a pre-existing bug that shows up in the touched lines of this PR. I do not insist on this.

@yadij accepting this dismissed your review; please re-approve

2024-12-19 10:21 UTC, yadij submitted a review, later dismissed

2024-12-19 13:27 UTC, rousskov commented
> I would like to get a concrete example of how it causes a measurable regression for you

I will work on providing one, but it will take me some time to simulate the problems I experience when searching for errors in large GitHub Action console output and to check suspicious assertions in your response to my review. I seriously doubt that spending this time is the best use of our scarce resources, but c'est la vie.

> > I would support adding the tail of a failed log to test-builds.sh output (even by default).

> It can help, but not as much as having the full log. Sometimes, especially in cases of high parallelism in builds, an error can be dozens of lines back from the end of the log

We can easily tail "dozens of lines". Obviously, the interesting bits may not be present in any partial output, but the full log is always a few mouse clicks/seconds away.

2024-12-19 16:56 UTC, kinkie commented
> > I would like to get a concrete example of how it causes a measurable regression for you
> 
> 
> 
> I will work on providing one, but it will take me some time to simulate the problems I experience when searching for errors in large GitHub Action console output and to check suspicious assertions in your response to my review. I seriously doubt that spending this time is the best use of our scarce resources, but c'est la vie.

I agree you should not spend the time! I do not understand what the problem is, to be honest. You would not be forced to search for errors in large console output, your current way of operating will not be taken away from you or anyone else.
As you say, the full log is always a few clicks away. In fact, it would be exactly the same clicks away as it is now

2024-12-19 18:01 UTC, rousskov commented
> I agree you should not spend the time! I do not understand what the problem is, to be honest. 

Glad we agree. Unfortunately, I do not see how I can explain what the problem is and address your rebuttal of my blocking review without spending that time. Clearly, my initial attempt to explain has failed. Now I need to validate my "this change makes things worse for primary use case" assumption with a specific example and, ideally, also illustrate that searching through large console logs for errors is not as easy as the author says. That takes time.

2024-12-19 18:15 UTC, kinkie commented
> > I agree you should not spend the time! I do not understand what the problem is, to be honest.
> 
> Glad we agree. Unfortunately, I do not see how I can explain what the problem is and address your rebuttal of my blocking review without spending that time. Clearly, my initial attempt to explain has failed. Now I need to validate my "this change makes things worse for primary use case" assumption with a specific example and, ideally, also illustrate that searching through large console logs for errors is not as easy as the author says. That takes time.

Sorry about that.
Hoping to be of help, could you walk me though your process with
https://github.com/squid-cache/squid/actions/runs/12408472448/job/34640210517 (one of the job runs for this same PR) as opposed to https://github.com/squid-cache/squid/actions/runs/12400872862/job/34619011412 (same job for PR 1964? It has (or at least should have) the exact same contents?

2024-12-19 20:30 UTC, rousskov commented
> could you walk me though your process with https://github.com/squid-cache/squid/actions/runs/12408472448/job/34640210517 (one of the job runs for this same PR) as opposed to https://github.com/squid-cache/squid/actions/runs/12400872862/job/34619011412 (same job for PR 1964? It has (or at least should have) the exact same contents?

Sure: My primary "process" for both of the given examples is the same -- I typically ignore successful builds. My primary concerns (in this PR scope) are not about the builds we ignore.

If you would like for me to stray from the primary path and use your [first example](https://github.com/squid-cache/squid/actions/runs/12408472448/job/34640210517) to illustrate some of the (secondary) problems, then keep reading.  *YMMV*, but when navigating large "Run build..." step logs using GitHub Actions web UI in my environment, I can observe the following:

1. GitHub Actions search UI lies about the number of times character sequence "error" occurs in that log. UI says 100. There are about 1922 matches in that build log AFAICT! The last "error" according to UI (i.e. "error" match number 100) is clearly not the last one. Thus, search -- a key function of any log navigation UI -- does not really work well here.
2. The browser only shows a portion of the log when using a scroll bar and "scrolling to the end" for the very first time after loading that page (before the entire log gets fetched/cached by UI code, I guess). I have to "scroll to the end" several times to get to the real end of the log. Needless to say, the end of the output is often the interesting part or the starting point. Thus, scrolling with a mouse -- another key GUI function -- does not work well here either. Using keyboard-based navigation appears to work, but some users may not know that they have not reached the end (using a scroll bar) or that navigating using keyboard works better.
 
AFAICT, longer logs exacerbate these problems. Certain errors may significantly increase log size. In general, logs tend to grow with time as well. The current example cannot illustrate that, of course.

Time spent so far: 37 minutes.

2024-12-19 23:08 UTC, kinkie commented
> > could you walk me though your process with https://github.com/squid-cache/squid/actions/runs/12408472448/job/34640210517 (one of the job runs for this same PR) as opposed to https://github.com/squid-cache/squid/actions/runs/12400872862/job/34619011412 (same job for PR 1964? It has (or at least should have) the exact same contents?
> 
> Sure: My primary "process" for both of the given examples is the same -- I typically ignore successful builds. My primary concerns (in this PR scope) are not about the builds we ignore.
> 
> If you would like for me to stray from the primary path and use your [first example](https://github.com/squid-cache/squid/actions/runs/12408472448/job/34640210517) to illustrate some of the (secondary) problems, then keep reading. _YMMV_, but when navigating large "Run build..." step logs using GitHub Actions web UI in my environment, I can observe the following:
> 
> 1. GitHub Actions search UI lies about the number of times character sequence "error" occurs in that log. UI says 100. There are about 1922 matches in that build log AFAICT! The last "error" according to UI (i.e. "error" match number 100) is clearly not the last one. Thus, search -- a key function of any log navigation UI -- does not really work well here.

Then don't use them, you can continue downloading the artefact and searching there. I'm not proposing to take that away

on top of that:
$ gh run view --job 34640210517 --log | grep error | wc -l
    2821

> 2. The browser only shows a portion of the log when using a scroll bar and "scrolling to the end" for the very first time after loading that page (before the entire log gets fetched/cached by UI code, I guess). I have to "scroll to the end" several times to get to the real end of the log. Needless to say, the end of the output is often the interesting part or the starting point. Thus, scrolling with a mouse -- another key GUI function -- does not work well here either. Using keyboard-based navigation appears to work, but some users may not know that they have not reached the end (using a scroll bar) or that navigating using keyboard works better.

Sure. After this PR lands - if ever - you can keep downloading the artefacts2 and search there

> AFAICT, longer logs exacerbate these problems. Certain errors may significantly increase log size. In general, logs tend to grow with time as well. The current example cannot illustrate that, of course.
> 
> Time spent so far: 37 minutes.

Sorry about that. Unfortunately I still do not see how this change will prevent you from continuing to operate in the same way you have so far, while allowing me to choose on a case by case basis whether to rely on the 2 additional workflows that will be available

I feel like my message is not getting through: you and anyone else who wants or needs to rely on the artefacts will be perfectly able to continue using artefacts, without ever seeing or interacting with the second copy of the output that is emitted to stdout/stderr. I am not encouraging, much less forcing, anyone to stop relying on artefacts as their primary - or only - source of debugging information.

You have so far not articulated any regression in functionality for yourself.
I feel that you are answering a different question than the one I've asked. My question was "how would your workflow be worse off if this lands", not "how is this functionality worse than the alternative in some cases"

2024-12-20 03:08 UTC, rousskov commented
> Francesco: could you walk me though your process with ...?

> Alex: [Walks through the process of using the referenced run pages, to the best of his ability].

> Francesco: I'm not proposing to take [your ability to download artifacts] away.

Yes, I am well aware of that fact (naturally?). None of my concerns state or imply otherwise!

> Unfortunately I still do not see how this change will prevent you from continuing to operate in the same way you have so far

I know. As I [said](https://github.com/squid-cache/squid/pull/1965#issuecomment-2555451307), I need to validate my assumption (that this change may make things worse for primary use case) with a specific example. That should overcome the current barriers, but it takes time. So far, I was just responding to your other (mostly unrelated) request.

We are making progress though because the second (and secondary) item from the same TODO has been completed: "illustrate that searching through large console logs for errors is not as easy as the author says".

> I feel like my message is not getting through: you and anyone else ... will be perfectly able to continue using artefacts ... I am not encouraging, much less forcing, anyone to stop relying on artefacts as their primary - or only - source of debugging information.

Your message is getting through just fine AFAICT. However, that message is not relevant to my change request[^1]. FWIW, the same situation happens in the vast majority of cases where the rebuttal is based on an obvious, surface-level, in-your-face fact that I ought to be aware of. There are always exceptional cases, of course!

[^1]: There are other red flags in that "message", but I want to stay focused on the primary problem.

> You have so far not articulated any regression in functionality

I believe my change request described my concerns reasonably well, but the level of "articulation"[^2] is naturally a matter of opinion, and I am sorry I failed to be articulate enough. I need more time to detail what has been described with an example, as discussed earlier, and I hope that example would help get us on the same page.

[^2]: Just to avoid misunderstanding, the level of "articulation" is is not the same as the level of detail. I did _not_ detail or illustrated my concerns (in hope to save time).

> My question was "how would your workflow be worse off if this lands", 

Not exactly AFAICT: My original review can already be used to answer this simpler "how things can become worse" question, at least on a superficial level. Your actual request [went](https://github.com/squid-cache/squid/pull/1965#issuecomment-2549929371) a lot further: "I would like to get a _concrete example_ of how it causes a _measurable_ regression for you". That is still a TODO for me.

> not "how is this functionality worse than the alternative in some cases"

It may be important to keep in mind that GitHub Actions GUI being discussed here is the primary/first/initial source of information for many, especially among less experienced/new contributors. _If_ a PR makes it worse (in some cases), then it is a valid argument against that PR, regardless of whether there are other/unaffected ways to obtain the same or similar info. This is an aggravating factor if you will. The task of proving that my concerns are valid (with a "concrete example" that demonstrates "measurable regression") is still a TODO on my side.

Time spent so far: 69 minutes.

2024-12-20 08:08 UTC, kinkie commented
> > Francesco: could you walk me though your process with ...?
> 
> > Alex: [Walks through the process of using the referenced run pages, to the best of his ability].
> 
> > Francesco: I'm not proposing to take [your ability to download artifacts] away.
> 
> Yes, I am well aware of that fact (naturally?). None of my concerns state or imply otherwise!
> 
> > Unfortunately I still do not see how this change will prevent you from continuing to operate in the same way you have so far
> 
> I know. As I [said](https://github.com/squid-cache/squid/pull/1965#issuecomment-2555451307), I need to validate my assumption (that this change may make things worse for primary use case) with a specific example. That should overcome the current barriers, but it takes time. So far, I was just responding to your other (mostly unrelated) request.
> 
> We are making progress though because the second (and secondary) item from the same TODO has been completed: "illustrate that searching through large console logs for errors is not as easy as the author says".
> 
> > I feel like my message is not getting through: you and anyone else ... will be perfectly able to continue using artefacts ... I am not encouraging, much less forcing, anyone to stop relying on artefacts as their primary - or only - source of debugging information.
> 
> Your message is getting through just fine AFAICT. However, that message is not relevant to my change request[1](#user-content-fn-1-dd706b195d5bf146578b5e1076b6f98d). FWIW, the same situation happens in the vast majority of cases where the rebuttal is based on an obvious, surface-level, in-your-face fact that I ought to be aware of. There are always exceptional cases, of course!
> 
> > You have so far not articulated any regression in functionality
> 
> I believe my change request described my concerns reasonably well, but the level of "articulation"[2](#user-content-fn-2-dd706b195d5bf146578b5e1076b6f98d) is naturally a matter of opinion, and I am sorry I failed to be articulate enough. I need more time to detail what has been described with an example, as discussed earlier, and I hope that example would help get us on the same page.

I am glad we are making progress. The original review comment states:
> I expect the result to be less convenient for many, especially when the build fails (which is the primary use case here IMO!):

We have progressed in that we agree that the primary focus should be the case of failed builds.

> > My question was "how would your workflow be worse off if this lands",

Let me reframe that: you evoked "many", whom we have not heard from yet, whom you expect would be inconvenienced in the primary use case of a build failure.

I countered that by evoking many, of whom I am one, who would [benefit in a measurable way](https://github.com/squid-cache/squid/pull/1965#issuecomment-2549929371) in a significant fraction of the occurrences of the primary use case (based on real world experience).

> Not exactly AFAICT: My original review can already be used to answer this simpler "how things can become worse" question, at least on a superficial level. Your actual request [went](https://github.com/squid-cache/squid/pull/1965#issuecomment-2549929371) a lot further: "I would like to get a _concrete example_ of how it causes a _measurable_ regression for you" (emphasis mine). That is still a TODO for me.

"How things can become worse" is not what I asked. How things _do_ become worse is what we need to find here. And so far the best concrete case you have presented is "someone who might contribute to the project might be tempted to use a sometimes less effective workflow" which is not particularly compelling: it applies in a fraction of a fraction of a fraction of events, and remediation is one github comment from one of us away - hardly a high barrier.

But then, once we have found an adverse example and assessed its likelihood of happening, we have to match that against the measurable benefit of the alternative (landing this PR) and then we can take an informed decision

2024-12-20 14:07 UTC, rousskov commented
> > > My question was "how would your workflow be worse off if this lands",
> 
> Let me reframe that: ...

IMO, the new framing and past "measurements" are rather unfair. I bet you disagree, but I hope we can continue to make progress even under these adverse conditions.

BTW, while we are talking about structuring the debate, we should keep in mind that the primary problem can be addressed in several ways. Where feasible, we should be selecting the "best feasible" way rather than dealing with a "this way or nothing" false dichotomy.

> > My original review can already be used to answer this simpler "how things can become worse" question, at least on a superficial level.
 
> "How things can become worse" is not what I asked. How things _do_ become worse is what we need to find here. 

We can use "do become" phrasing if you prefer: It is _your_ question, and you can shape it any way you like, of course. AFAICT, the next things I have to do are exactly the same regardless of that phrase choice ("would be worse", "can become worse", or "does become worse"). In other words, for me, all those variations are effectively the same in this context.

Overall, we are (or should be) evaluating expected PR outcomes. That set of outcomes is _not_ limited to a subset of cases one of us has already witnessed (or is asked to witness). We cannot afford to support every expectation with a test case. Where feasible, I hope we can continue to agree on judgement calls not backed by a dedicated test case. Said that, I will spend time to test my assumption in this case.

> And so far the best concrete case you have presented is "someone who is not experienced in how we do CI might turn up and contribute , and might be tempted to use a sometimes less effective workflow" which is not particularly compelling: it applies in a fraction of a fraction of a fraction of events, and remediation is one github comment from one of us away - hardly a high barrier.

I agree that the relative number of relevant events is small from our point of view[^1]. Our current chances of encountering a new contributor are small to begin with! It looks like I value new contributor satisfaction and my time spent to address contributor dissatisfaction much higher than you do (so my multiplier is much higher), but I hope we can make progress despite those valuation differences.

[^1]: On the other hand, that same "relevant event" probability is close to 100% from a new contributor point of view!

> once we have found an adverse example and assessed its likelihood of happening, we have to match that against the measurable benefit of the alternative (landing this PR) and then we can take an informed decision

Yes, we need to assess and balance expected benefits/harms; that will require judgement calls, and, FWIW, I will continue to place a high premium on new contributor experience. And, again, rejecting or landing current PR code are not the only two alternatives we should be considering.

Time spent so far: 131 minutes.

2024-12-21 17:15 UTC, kinkie commented
> > > > My question was "how would your workflow be worse off if this lands",
> > 
> > 
> > Let me reframe that: ...
> 
> IMO, the new framing and past "measurements" are rather unfair. I bet you disagree, but I hope we can continue to make progress even under these adverse conditions.

You are right, I disagree. But I also hope we can progress

> BTW, while we are talking about structuring the debate, we should keep in mind that the primary problem can be addressed in several ways. Where feasible, we should be selecting the "best feasible" way rather than dealing with a "this way or nothing" false dichotomy.

If "best feasible" is the goal, the solution gets naturally biased to "more options are better than fewer options" just by virtue of having more choice, but I bet you disagree ;)

> > > My original review can already be used to answer this simpler "how things can become worse" question, at least on a superficial level.
> 
> > "How things can become worse" is not what I asked. How things _do_ become worse is what we need to find here.
> 
> We can use "do become" phrasing if you prefer: It is _your_ question, and you can shape it any way you like, of course. AFAICT, the next things I have to do are exactly the same regardless of that phrase choice ("would be worse", "can become worse", or "does become worse"). In other words, for me, all those variations are effectively the same in this context.

Well, in terms of risk, "can become worse" or "would be worse" is about the likelihood of becomign worse. "do become" requies certainty, or at least a high-confidence prediction

> Overall, we are (or should be) evaluating expected PR outcomes. That set of outcomes is _not_ limited to a subset of cases one of us has already witnessed (or is asked to witness). We cannot afford to support every expectation with a test case. Where feasible, I hope we can continue to agree on judgement calls not backed by a dedicated test case. Said that, I will spend time to test my assumption in this case.

I agree we should not spend infinite amounts of time on wild goose chases.
At the same time, I hope you agree we need to bias our reasoning to maximise impact, which we can define using a common definition of impact: effect of an event multiplied by its likelihood. (e.g. we should assess the impact of buying a lottery ticket [£2.50 * 1 today] against the impact of winning the lottery [£22m * 0.00000001 today])

> > And so far the best concrete case you have presented is "someone who is not experienced in how we do CI might turn up and contribute , and might be tempted to use a sometimes less effective workflow" which is not particularly compelling: it applies in a fraction of a fraction of a fraction of events, and remediation is one github comment from one of us away - hardly a high barrier.
> 
> I agree that the relative number of relevant events is small from our point of view[1](#user-content-fn-1-16323293a5a13ce8b21a878199973eaa). Our current chances of encountering a new contributor are small to begin with!

Yes, unfortunately.

> It looks like I value new contributor satisfaction and my time spent to address contributor dissatisfaction much higher than you do (so my multiplier is much higher), but I hope we can make progress despite those valuation differences.

I disagree with this statement, in part because you are misassessing what I value, in part because it feels you are assuming that a new contributor would be dissatisfied by having more options to choose among - and we do not even know that!
In fact, my assumption would be exactly the opposite: that a new contributor (and at least one existing one, possibly two looking at the current PR approvals) would be more satisfied by having more options, even though not all options are ideal for all use cases

> > once we have found an adverse example and assessed its likelihood of happening, we have to match that against the measurable benefit of the alternative (landing this PR) and then we can take an informed decision
> 
> Yes, we need to assess and balance expected benefits/harms; that will require judgement calls, and, 

> FWIW, I will continue to place a high premium on new contributor experience.

We share the goal. Problem is, so far we can't agree on what is that would make new developers' experience as good as we can.
Two problems:
1. new contributors are hypotheticals so far in that none chimed in in this discussion, while existing contributors are a certainty; and
2. we do not know what would make a new developer's experience better among the options we have on the table so far. We can try to guess, but your and my guesses differ


> And, again, rejecting or landing current PR code are not the only two alternatives we should be considering.

I appreciate you offered to print some lines from the output, but I feel it is a worse choice than printing everything. Do you have any alternative idea to propose?


> Time spent so far: 131 minutes.
> 
> ## Footnotes
> 1. On the other hand, that same "relevant event" probability is close to 100% from a new contributor point of view! [↩](#user-content-fnref-1-16323293a5a13ce8b21a878199973eaa)

We do not know this. It would be great if any new developer could chime in here!

2024-12-22 02:04 UTC, rousskov commented
I see no progress in the last exchange -- just another round full of misinterpretations and false assumptions. We can probably clarify most of them in a few rounds, but I doubt its worth the cost, so I suggest that we pause. I hope that my next message will discuss a specific error example that demonstrates or dismisses the alleged PR problem. It will take time to construct that, but I do plan on doing it.

2025-02-01 22:24 UTC, rousskov requested changes
> I hope that my next message will discuss a specific error example that demonstrates or dismisses the alleged PR problem. It will take time to construct that, but I do plan on doing it.

Done: I have now performed the previously missing tests for a primary use case and can confirm that this PR makes things worse. With PR changes:

* [Linux](https://github.com/measurement-factory/squid/actions/runs/13091419054/job/36528471937): GitHub's "automatically scroll to error" or similar feature helps skip the added noise to arrive at the error reporting line, but that error line is now separated from additional/important error details that are all grouped together in [official code output](https://github.com/measurement-factory/squid/actions/runs/13092473061/job/36530745334) for the same injected error.

* [FreeBSD](https://github.com/measurement-factory/squid/actions/runs/13091419054/job/36528471870): GitHub's "automatically scroll to error" or similar feature does not work, "find in page" and even "scroll to end" navigation do not always work (without special efforts). With those impediments, the error is even more difficult to find in PR log (compared to [official code output](https://github.com/measurement-factory/squid/actions/runs/13092473061/job/36530745135)) due to PR-added output on top of the error.

* In both cases, the new console log now contains repeated out-of-order lines in non-error cases, complicating correct test interpretation/navigation. This regression is essentially a bad side effect of the existing problematic `test-builds.sh --verbose` implementation (that this PR proposes to use for CI tests).

Going forward, I see two viable options for this PR:

1. Undo current workflow changes. Refactor test-builds.sh approach to logging: Drop `test-builds.sh --verbose` support. Unconditionally send all script (including build) output to stdout and stderr. Let the script _caller_ capture zero, one, or both of those two streams, depending on caller's needs (e.g., redirecting stdout to /dev/null). Unconditionally use GitHub Actions `::group::` markup to separate layer-specific output into collapsable sections. In GitHub CI workflows, rely on existing/GitHub automatic logging instead of capturing output into files. This option arguably makes test-builds.sh approach to output more Unix or `make`-like, giving callers more integration options.

2. Keep current workflow changes. Adjust `test-builds.sh` so that (when `--verbose` build is enabled), the script surrounds `tee $1` output with GitHub Actions `::group::` markup to send the full build log into a dedicated _collapsable_ section (with layer name in the title). This option requires very little additional work.

I hope that with either option, those who want to see full output on GitHub Actions "console" would be able to do so (by expanding the corresponding reporting section). And those who want to see essential log lines (first), would be able to do so as well (by _not_ expanding the corresponding reporting section until they need it).

@kinkie, would any of those two options work well for you?

N.B. For `::group::` and similar GitHub Actions markup examples, search for `::` characters in test-functionality.sh.

P.S. We should also improve test-builds.sh to reduce noise, including removing `FAIL: 0` lines and duplicated `error:` lines. That work is outside this PR scope though.

Time spent so far: 5 hours and 26 minutes

2025-02-13 14:32 UTC, rousskov requested changes

2025-02-13 14:32 UTC, rousskov commented on .github/workflows/quick.yaml
> +          ./test-builds.sh --verbose ${{ matrix.layer.name }}
Thank you for advancing this PR. The latest PR attempt looks much closer to item 2 than it is to item 1 from my earlier [review](https://github.com/squid-cache/squid/pull/1965#pullrequestreview-2588420971). I support that choice.

> 2. Keep current workflow changes. Adjust `test-builds.sh` so that (when `--verbose` build is enabled), the script surrounds `tee $1` output with GitHub Actions `::group::` markup to send the full build log into a dedicated _collapsable_ section (with layer name in the title). This option requires very little additional work.

However, the proposed implementation still introduces the _very same problem_ that those suggestions were trying to avoid!

Please redo, using quoted item 2 as a blueprint.

* If you do not know what problem the current PR implementation creates, we can re-discuss it during the next meeting _or_ just follow the blueprint.
* If the latest attempt was using item 2 as a blueprint already, please reread that item carefully, especially the part that talks about modifying test-builds.sh (rather than YAML workflows).

Time spent so far: 5 hours and 42 minutes

2025-02-16 23:54 UTC, kinkie commented
> > I hope that my next message will discuss a specific error example that demonstrates or dismisses the alleged PR problem. It will take time to construct that, but I do plan on doing it.
> 
> Done: I have now performed the previously missing tests for a primary use case and can confirm that this PR makes things worse. With PR changes:
> 
> * [Linux](https://github.com/measurement-factory/squid/actions/runs/13091419054/job/36528471937): GitHub's "automatically scroll to error" or similar feature helps skip the added noise to arrive at the error reporting line, but that error line is now separated from additional/important error details that are all grouped together in [official code output](https://github.com/measurement-factory/squid/actions/runs/13092473061/job/36530745334) for the same injected error.

FTR: I have no plan, and we have never referred to, any such feature. Whether it works or  not is irrelevant to the current discussion. Finding errors in stdout, or in a downloaded stdout has the same effort, except for the additional effort in downloading.
The factor which makes identifying errors the hardest is parallel build, which has nothing to do with where the output is sent to. Failure to compile a unit can easily be tens of lines before the end of output due to that, mingled with build output from other directories even. However, we do not want to remove parallel build as a feature, on hosted github actions it cuts test wall clock time by 75%.

> * [FreeBSD](https://github.com/measurement-factory/squid/actions/runs/13091419054/job/36528471870): GitHub's "automatically scroll to error" or similar feature does not work, "find in page" and even "scroll to end" navigation do not always work (without special efforts). With those impediments, the error is even more difficult to find in PR log (compared to [official code output](https://github.com/measurement-factory/squid/actions/runs/13092473061/job/36530745135)) due to PR-added output on top of the error.
> * In both cases, the new console log now contains repeated out-of-order lines in non-error cases, complicating correct test interpretation/navigation. This regression is essentially a bad side effect of the existing problematic `test-builds.sh --verbose` implementation (that this PR proposes to use for CI tests).

This argument is irrelevant, as the ability to download artifacts is preserved for anyone wishing to have a more detailed view. FWIW, I would be perfectly fine in adding code that printed that message out in github-hosted builds to direct anyone who isn't experienced to the artifacts.

> Going forward, I see two viable options for this PR:
> 
> 1. Undo current workflow changes. Refactor test-builds.sh approach to logging: Drop `test-builds.sh --verbose` support. Unconditionally send all script (including build) output to stdout and stderr. Let the script _caller_ capture zero, one, or both of those two streams, depending on caller's needs (e.g., redirecting stdout to /dev/null). Unconditionally use GitHub Actions `::group::` markup to separate layer-specific output into collapsable sections. In GitHub CI workflows, rely on existing/GitHub automatic logging instead of capturing output into files. This option arguably makes test-builds.sh approach to output more Unix or `make`-like, giving callers more integration options.
> 2. Keep current workflow changes. Adjust `test-builds.sh` so that (when `--verbose` build is enabled), the script surrounds `tee $1` output with GitHub Actions `::group::` markup to send the full build log into a dedicated _collapsable_ section (with layer name in the title). This option requires very little additional work.
> 
> I hope that with either option, those who want to see full output on GitHub Actions "console" would be able to do so (by expanding the corresponding reporting section). And those who want to see essential log lines (first), would be able to do so as well (by _not_ expanding the corresponding reporting section until they need it).
> 
> @kinkie, would any of those two options work well for you?

Implemented option 2, or at least my understanding of it

> 
> N.B. For `::group::` and similar GitHub Actions markup examples, search for `::` characters in test-functionality.sh.
> 
> P.S. We should also improve test-builds.sh to reduce noise, including removing `FAIL: 0` lines and duplicated `error:` lines. That work is outside this PR scope though.

Yes. These are printed to stdout by the automake parallel test harness

> Time spent so far: 5 hours and 26 minutes

2025-02-17 16:31 UTC, rousskov reviewed
> > Alex: Done: I have now performed the previously missing tests for a primary use case and can confirm that this PR makes things worse.  [...]

> Francesco: Whether [a certain GitHub Actions feature] works or not is irrelevant to the current discussion. [...]  This argument is irrelevant, as the ability to download artifacts is preserved for anyone wishing to have a more detailed view

I illustrated how the earlier PR implementation made things worse in certain use cases. Those illustrations/problems were relevant to evaluating PR implementation pros and cons. Yes, one can avoid certain problems by downloading artifacts, but the problems I was describing are with using GitHub Actions UI. The recommendation to start avoiding GitHub Actions UI in certain old use cases is a con. Certainly, GitHub Actions UI enjoyment is a valid evaluation criteria -- if "just download artifacts!" were always the right answer (it is not!), then this PR itself would not be needed.

> Implemented option 2

Thank you. The new implementation addresses my primary "increased noise" concern, so I am dismissing my earlier blocking review.

I have also updated PR description to match the current implementation. Please check and adjust further as needed.

_Disclaimer_: I have not reviewed multi-layer output from certain slow.yaml tests because none was provided at the time of this review, and I decided not to spend time on making a sample myself.

Time spent so far: 5 hours and 57 minutes

2025-02-18 06:09 UTC, kinkie commented
Thanks.. clearing for merge; I'll review the slow.yaml output and make sure multi-layer builds work fine, and follow up if they don't

2025-02-18 06:10 UTC, closed without merging

2025-02-18 06:40 UTC, kinkie commented
The FAIL/XFAIL lines are still shown. Fixing it is out of scope for this, but yes, that is annoying; I'll see what I can do about it

2025-02-18 16:16 UTC, rousskov commented
> The FAIL/XFAIL lines are still shown. ... I'll see what I can do about it

Thank you! AFAICT, we need to fix `errors` regex in test-builds.sh to stop matching `# *X?FAIL:` statistics lines while still matching FAIL lines produced by failing CppUnit tests (IIRC).

2025-02-18 22:45 UTC, kinkie commented
> > Alex: I have not reviewed multi-layer output from certain slow.yaml tests because none was provided at the time of this review, and I decided not to spend time on making a sample myself.
> 
> > Franceso: I'll review the slow.yaml output and make sure multi-layer builds work fine, and follow up if they don't
> 
> I regret letting this PR merge without checking slow.yaml results :-(. @kinkie, please post a PR to revert the changes made in this PR (i.e. master/v8 commit [e5a66fc](https://github.com/squid-cache/squid/commit/e5a66fc26dae3806cdd12ee767e85b1d6837384d)):
> 
> It looks like GitHub UI designers share my overall "excessive noise" and "overwhelmed UI" concerns and effectively disable the feature added in this PR for [builds](https://github.com/squid-cache/squid/actions/runs/13374829207/job/37351601868) with arguably excessive noise levels:
> 
> ![Screenshot 2025-02-18 at 9 56 22 AM](https://private-user-images.githubusercontent.com/1084944/414317750-e45b428a-fbaa-48da-8dbc-286f4ddeef2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk5MTg0NjAsIm5iZiI6MTczOTkxODE2MCwicGF0aCI6Ii8xMDg0OTQ0LzQxNDMxNzc1MC1lNDViNDI4YS1mYmFhLTQ4ZGEtOGRiYy0yODZmNGRkZWVmMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMThUMjIzNjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJlMjQ4NzU2OWNkNGRjZDZjZGFkZWMyNjg0ZjE1ODYzOWYyNDgzOGQ0ZGE2ZDRkOGRhZjZjYzZkZTAxYzNlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.itltKTTnaHc_78Fly8McvcFrkWaJV7kbGHykzo5lKJU)
> 
> Unfortunately, the above GitHub hack kills _essential_ output as well -- GitHub Actions UI no longer shows any errors and warnings that happen after the above suppression is activated (which, in this case, happens _during_ the first/default layer build).

Is the screenshot taken from the [build job you linked?](https://github.com/squid-cache/squid/actions/runs/13374829207/job/37351601868) Because it looks different to me:

<img width="996" alt="Screenshot 2025-02-19 at 06 42 12" src="https://github.com/user-attachments/assets/4e91107e-3f46-4e5c-889a-c8c76f7a2fce" />

Could it be that the reason is the browser/system you are watching it with? I am using Chrome on MacOS/arm64

Now, this approach has a downside compared to just including output : the collapsable section is implemented in javascript; opening it takes minutes - I suppose it's all async http requests in the background

> Also, this PR missed openbsd build modifications. That job is missing `--verbose`.
I guess a followup PR is due one way or another. Let's decide which direction first