Do not forward malformed warning-values
squid-cache/squid pull request #805
Opened 2021-04-19 14:43 UTC by rousskov

Since we started policing Warning header field values (commit c679653),
Squid was preserving some malformed warning-values and removing some
other malformed warning-values. I speculate that inconsistency was a
bug. Now we consistently remove all malformed warning-values we detect.

2021-04-19 14:49 UTC, rousskov commented
Disclaimer: This change has not been tested yet.

2021-04-19 15:13 UTC, MegaManSec commented
Thank you for this!

I can, at the very least, say this now makes the Warning header behave the way I would expect it to.

2021-04-20 21:24 UTC, yadij commented on src/HttpReply.cc
>      const char *pos = 0;
Before merge, please correct these to nullptr initialization. This is technically a new function even though it shares a lot of syntax with the old one.

2021-04-20 21:24 UTC, yadij approved these changes
LGTM

2021-04-20 21:34 UTC, yadij requested changes
Actually. Design breaks HTTP spec.  warn-data is optional. That is what the old keep=true initialization was about, to keep entries without a warn-date.

It looks like this design discards by omission when time<=0. It should consider those "fresh" for v1.1+. We apparently lack the logic detecting v1.0 where warn-date was mandatory.

2021-04-26 00:52 UTC, yadij requested changes

2021-04-26 00:52 UTC, yadij commented on src/HttpReply.cc
> +                if (time > 0 && time == date) { // valid and matching
```suggestion
                if (time > 0 && time != date)
                    continue; // invalid date field found
                if (time <= 0 && http_ver == Http::ProtocolVersion(1,0))
                    continue; // HTTP/1.0 requires date field on Warning headers
            }

```

2021-04-26 00:52 UTC, yadij commented on src/HttpReply.cc
> +                }
```suggestion
```

2021-04-29 22:40 UTC, rousskov commented
> Design breaks HTTP spec. warn-data is optional. That is what the old keep=true initialization was about, to keep entries without a warn-date.

Agreed. I suggest closing this PR then without committing anything. The original code is not as broken if warnings without warn-date must be kept in some messages. And, FWIW, I am not a big fan of making traffic policing decisions based on HTTP protocol minor version (where they can be avoided) -- too many exceptions in that area.

I can also rewrite the PR to just add a source code comment to explain `keep = true`.

@yadij, what is your preference?

2021-04-30 05:11 UTC, yadij commented
> @yadij, what is your preference?

Patches reducing brokenness are just as welcome as perfectly complete ones IMO. Up to you how you do that.

2021-04-30 13:24 UTC, rousskov commented
Closing because the problem is much smaller (and different) than thought, and I personally do not have the time for the minor (but likely contentions) adjustments that are necessary to improve this code further. This closure has no bearing on future pull requests improving this code; quality improvements are still welcomed, of course.

2021-04-30 13:24 UTC, closed without merging