Bug 5129: RequestMethod has custom assignment without copy constructor
squid-cache/squid pull request #825
Opened 2021-05-15 09:45 UTC by yadij

Remove unused Lock from HttRequestMethod
Resolves the need for broken copy operator and fixes
several compiler and static analysis warnings.

2021-05-15 10:23 UTC, kinkie approved these changes
Nice! You make it seem easy 🤣

2021-05-15 10:27 UTC, yadij commented
The main problem is that Lock allows copy in the first place. That is still not resolved and my latest attempt to fix there shows several other classes having the same issue as HttpRequestMethod which may actually need to stay RefCountable.

2021-05-15 15:43 UTC, rousskov requested changes
Please remove HttpRequestMethodPointer.

P.S. I did not see this PR when commenting on bug 5129.

2021-05-16 21:01 UTC, rousskov approved these changes
Thank you for polishing this PR up.

I fixed the PR description: The assignment operator is still needed/used, we just do not need to customize it. It is that explicit declaration and customization that triggered problems, not the operator itself. Please adjust further if needed.

2021-05-17 16:58 UTC, closed without merging