Ssl masterkey cant be nullptr
squid-cache/squid pull request #848
Opened 2021-06-16 13:14 UTC by kinkie

Compatibility fix for SSL session->master_key

SSL_SESSION::master_key is an array data member of
SSL_SESSION. As such, it can't be nullptr

Prior to this PR, the issue is highlighted as a
pedantic error in arm32/ubuntu-xenial/clang

`
compat/openssl.h:178:35: error: address of array 'session->master_key' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
`

2021-06-16 14:20 UTC, rousskov requested changes
> SSL_SESSION::master_key is an array

Not always. Have you seen the corresponding Coverity triage [note](https://scan5.coverity.com/reports.htm#v46217/p10191/fileInstanceId=194348256&defectInstanceId=51558848&mergedDefectId=1485164) for CID 1485164?

2021-06-16 14:30 UTC, kinkie commented
I had not ,thanks for highlighting.
I guess preprocessor magic will be needed to cover both cases, or some way to disable this specific check here. It doesn't add a lot of value anyway

2021-06-16 14:46 UTC, rousskov commented
> I guess preprocessor magic will be needed to cover both cases, or some way to disable this specific check here. It doesn't add a lot of value anyway

Perhaps there is still a misunderstanding: This is a runtime tls_key_log bug -- in some (still relatively popular) environments, the code is not checking what it should be checking and then probably not even accessing what it should be accessing after the checks succeeds. The compiler warning is just a side effect of that bug. This bug needs fixing, but the fix is not trivial due to OpenSSL `struct` layout changes. Most likely, the correct fix will be driven by ./configure-time tests of OpenSSL `struct` layouts that Squid is being built with.

2021-06-17 13:48 UTC, kinkie commented
Closing the PR and runnign some tests behind the scenes. I'll reopen it once a workable solution is found

2021-06-24 20:59 UTC, rousskov commented
> Alex: OpenSSL SSL_SESSION structure layout has changed. ... I suspect that the reinterpret_cast<> assumes the wrong layout

I think I figured it out. I was looking at `ssl_session_asn1_st` structure, which did change. I was looking at the wrong structure though! Instead, we should be looking at `ssl_session_st` structure, which did _not_ change (as far as master_key is concerned). 

In the `ssl_session_st` structure, the master_key is an array in all those older OpenSSL versions. We do not need to test master_key for being nil, and the reinterpret_cast is not terribly wrong (that cast may not be needed at all, but that is a different and very minor problem).

@kinkie, do you want to reopen this PR and remove the unnecessary "master_key is not nil" check (no other changes should be needed compared to master)? Alternatively, I can remove that check in a new branch/PR. Your call.

2021-06-24 21:39 UTC, kinkie commented
I'll reopen this, clean it and submit again. The work is already done, after all

2021-06-25 00:10 UTC, rousskov approved these changes
Thank you for fixing this! Please check that my PR title/description edits are OK with you and adjust further as needed.

I wonder whether there is a simple static_assert that can flag this code if OpenSSL changes the master_key type to become a pointer, but I do not have the time to investigate that right now.

2021-06-25 07:31 UTC, closed without merging