Fix tcp keepalive
squid-cache/squid pull request #853
Opened 2021-07-05 13:09 UTC by yadij

Setting the keep-alive flags for TCP at the same time as
other flags resolves issues with client sockets timing out
while waiting for the ::Server handler to run.

Also, resolves a bug with FTP DATA connections not having
keep-alive set. These connections would truncate objects
if the tranfer connection paused too long and became timed
out by the network routing system.

Also, minor polishing to the comm API simplifying use of
this TCP feature.

2021-07-05 15:01 UTC, rousskov requested changes
Nice fix, thank you! I do not insist on any of the changes in this review except for one (marked as such).

2021-07-05 16:00 UTC, rousskov commented
I adjusted PR description, primarily to fix spelling and improve formatting. The API adjustments are natural/obvious/ and do not have to be explicitly disclosed/justified IMO so I removed the last paragraph. Please adjust further if needed.

2021-07-06 08:48 UTC, yadij commented on src/comm.h
> +void commSetTcpKeepalive(int fd, const AnyP::PortCfg::TcpKeepalive &);
Done. Will push shortly.

2021-07-06 08:48 UTC, yadij commented on src/comm.cc
> +        return;
Done. will push shortly

2021-07-08 15:34 UTC, rousskov commented
I pushed a few polishing changes. Please adjust as needed. If I get a chance before this is merged, I will self-request a review and polish the moved code further.

2021-07-12 13:31 UTC, yadij commented
Additions so far look good to me.

2021-07-13 22:28 UTC, rousskov reviewed
I am done modifying the code. Please adjust further as needed, of course. My commit 16badfa implies that this code was not properly tested. Please do test your PRs!

2021-08-01 18:34 UTC, closed without merging