Remove step2+ stare-and-splice and peek-and-bump support
squid-cache/squid pull request #926
Opened 2021-10-30 07:04 UTC by chtsanti

Support for these features was successfully disabled (at build time) for
five years. See commit 88a300c for the list of reasons. We did not even
provide an ./configure --enable-... option for it. The corresponding
code does not compile with modern OpenSSL versions, but its mere
presence complicates related code logic and significantly increases
related development efforts. This code is not worth keeping.

This is a Measurement Factory project.

2021-10-30 10:33 UTC, yadij approved these changes
Excellent news. Thank you.

2021-10-30 10:35 UTC, yadij requested changes
There is a use of SQUID_CHECK_OPENSSL_HELLO_OVERWRITE_HACK in configure.ac which also needs to be removed.

2021-10-31 07:16 UTC, chtsanti commented
> There is a use of SQUID_CHECK_OPENSSL_HELLO_OVERWRITE_HACK in configure.ac which also needs to be removed.

commit ac5564ae1

2021-11-01 12:31 UTC, yadij approved these changes

2021-11-01 14:19 UTC, closed without merging